# Generated by Django 5.1.5 on 2025-02-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_name',
            new_name='subject_name',
        ),
    ]
