# Generated by Django 5.1.5 on 2025-02-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
